name: pytest

on:
  push:

jobs:
  flake8-pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        poetry-version: [1.2.1]
        # os: [ubuntu-18.04, macos-latest, windows-latest]
        # os: [ubuntu-18.04, windows-latest]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Extra install for linux and non-linux
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            poetry run pip install data\\artifects\\pycld2-0.41-cp38-cp38-win_amd64.whl
            poetry run pip install data\\artifects\\PyICU-2.8.1-cp38-cp38-win_amd64.whl
          elif [ "$RUNNER_OS" == "macOS" ]; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            brew install pkg-config icu4c  # macOS
          else
            sudo apt install libicu-dev
            poetry run pip install pyicu==2.8 pycld2  # Linux
          fi
        shell: bash
      - name: Install packages
        run: |
          # sudo apt install libicu-dev pkg-config
          poetry run pip install fasttext
          poetry run pip install https://github.com/ffreemt/ezbee/raw/main/data/artifects/polyglot-16.7.4.tar.gz
          poetry install  # --no-dev
      - name: Run flake8
        run: |
          poetry run flake8 --exit-zero
          # poetry run pytest
      - name: Run pytest
        run: poetry run pytest tests
