name: ubuntu-pytest

on:
  push:

jobs:
  flake8-pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8.15]
        poetry-version: [1.2.2]
        # os: [ubuntu-18.04]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install packages
        run: |
          # sudo apt-get install libicu-dev pkg-config
          poetry run pip install fasttext
          poetry install  # --no-dev
          poetry add pyicu==2.8 pycld2
      - name: Run flake8
        run: |
          poetry run flake8 --exit-zero
          # poetry run pytest
      - name: Run pytest
        # run: poetry run pytest tests -k test_color_map -k test_sanity -k test_loadtext.py::test1 -k test_shakespeare1000
        run: poetry run pytest tests
